# Generated by Django 6.0.7 on 2026-07-14 15:13

import django.db.models.deletion
import game.logic
import game.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('active', 'In progress'), ('finished', 'Finished')], default='waiting', max_length=10)),
                ('board', models.JSONField(default=game.logic.empty_board)),
                ('current_turn', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=6)),
                ('remaining_pieces', models.JSONField(default=game.models.all_pieces)),
                ('last_piece', models.CharField(blank=True, default='', max_length=3)),
                ('is_blocked', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_seats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('piece', models.CharField(max_length=3)),
                ('orientation', models.PositiveSmallIntegerField()),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.gameplayer')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'color'), name='unique_color_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='unique_move_number'),
        ),
    ]
