# Generated by Django 6.0.2 on 2026-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameplayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='human_seats',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
